/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdvancedExtractClassificationRequest', 'model/AdvancedExtractFieldsRequest', 'model/DocumentAdvancedClassificationResult', 'model/DocumentCategories', 'model/DocumentClassificationResult', 'model/DocumentPolicyRequest', 'model/DocumentPolicyResult', 'model/ExtractBarcodesAiResponse', 'model/ExtractDocumentBatchJobResult', 'model/ExtractDocumentJobStatusResult', 'model/ExtractFieldsAndTablesResponse', 'model/ExtractFieldsResponse', 'model/ExtractTablesResponse', 'model/ExtractTextResponse', 'model/ExtractedBarcodeItem', 'model/ExtractedTextPage', 'model/FieldToExtract', 'model/FieldValue', 'model/PolicyRule', 'model/PolicyRuleViolation', 'model/SummarizeDocumentResponse', 'model/TableResult', 'model/TableResultCell', 'model/TableResultRow', 'api/AnalyzeApi', 'api/ExtractApi', 'api/RunBatchJobApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AdvancedExtractClassificationRequest'), require('./model/AdvancedExtractFieldsRequest'), require('./model/DocumentAdvancedClassificationResult'), require('./model/DocumentCategories'), require('./model/DocumentClassificationResult'), require('./model/DocumentPolicyRequest'), require('./model/DocumentPolicyResult'), require('./model/ExtractBarcodesAiResponse'), require('./model/ExtractDocumentBatchJobResult'), require('./model/ExtractDocumentJobStatusResult'), require('./model/ExtractFieldsAndTablesResponse'), require('./model/ExtractFieldsResponse'), require('./model/ExtractTablesResponse'), require('./model/ExtractTextResponse'), require('./model/ExtractedBarcodeItem'), require('./model/ExtractedTextPage'), require('./model/FieldToExtract'), require('./model/FieldValue'), require('./model/PolicyRule'), require('./model/PolicyRuleViolation'), require('./model/SummarizeDocumentResponse'), require('./model/TableResult'), require('./model/TableResultCell'), require('./model/TableResultRow'), require('./api/AnalyzeApi'), require('./api/ExtractApi'), require('./api/RunBatchJobApi'));
  }
}(function(ApiClient, AdvancedExtractClassificationRequest, AdvancedExtractFieldsRequest, DocumentAdvancedClassificationResult, DocumentCategories, DocumentClassificationResult, DocumentPolicyRequest, DocumentPolicyResult, ExtractBarcodesAiResponse, ExtractDocumentBatchJobResult, ExtractDocumentJobStatusResult, ExtractFieldsAndTablesResponse, ExtractFieldsResponse, ExtractTablesResponse, ExtractTextResponse, ExtractedBarcodeItem, ExtractedTextPage, FieldToExtract, FieldValue, PolicyRule, PolicyRuleViolation, SummarizeDocumentResponse, TableResult, TableResultCell, TableResultRow, AnalyzeApi, ExtractApi, RunBatchJobApi) {
  'use strict';

  /**
   * Use_next_generation_AI_to_extract_data_fields_insights_and_text_from_documents__Instantly_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CloudmersiveDocumentaiapiClient = require('index'); // See note below*.
   * var xxxSvc = new CloudmersiveDocumentaiapiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CloudmersiveDocumentaiapiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CloudmersiveDocumentaiapiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CloudmersiveDocumentaiapiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.3.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AdvancedExtractClassificationRequest model constructor.
     * @property {module:model/AdvancedExtractClassificationRequest}
     */
    AdvancedExtractClassificationRequest: AdvancedExtractClassificationRequest,
    /**
     * The AdvancedExtractFieldsRequest model constructor.
     * @property {module:model/AdvancedExtractFieldsRequest}
     */
    AdvancedExtractFieldsRequest: AdvancedExtractFieldsRequest,
    /**
     * The DocumentAdvancedClassificationResult model constructor.
     * @property {module:model/DocumentAdvancedClassificationResult}
     */
    DocumentAdvancedClassificationResult: DocumentAdvancedClassificationResult,
    /**
     * The DocumentCategories model constructor.
     * @property {module:model/DocumentCategories}
     */
    DocumentCategories: DocumentCategories,
    /**
     * The DocumentClassificationResult model constructor.
     * @property {module:model/DocumentClassificationResult}
     */
    DocumentClassificationResult: DocumentClassificationResult,
    /**
     * The DocumentPolicyRequest model constructor.
     * @property {module:model/DocumentPolicyRequest}
     */
    DocumentPolicyRequest: DocumentPolicyRequest,
    /**
     * The DocumentPolicyResult model constructor.
     * @property {module:model/DocumentPolicyResult}
     */
    DocumentPolicyResult: DocumentPolicyResult,
    /**
     * The ExtractBarcodesAiResponse model constructor.
     * @property {module:model/ExtractBarcodesAiResponse}
     */
    ExtractBarcodesAiResponse: ExtractBarcodesAiResponse,
    /**
     * The ExtractDocumentBatchJobResult model constructor.
     * @property {module:model/ExtractDocumentBatchJobResult}
     */
    ExtractDocumentBatchJobResult: ExtractDocumentBatchJobResult,
    /**
     * The ExtractDocumentJobStatusResult model constructor.
     * @property {module:model/ExtractDocumentJobStatusResult}
     */
    ExtractDocumentJobStatusResult: ExtractDocumentJobStatusResult,
    /**
     * The ExtractFieldsAndTablesResponse model constructor.
     * @property {module:model/ExtractFieldsAndTablesResponse}
     */
    ExtractFieldsAndTablesResponse: ExtractFieldsAndTablesResponse,
    /**
     * The ExtractFieldsResponse model constructor.
     * @property {module:model/ExtractFieldsResponse}
     */
    ExtractFieldsResponse: ExtractFieldsResponse,
    /**
     * The ExtractTablesResponse model constructor.
     * @property {module:model/ExtractTablesResponse}
     */
    ExtractTablesResponse: ExtractTablesResponse,
    /**
     * The ExtractTextResponse model constructor.
     * @property {module:model/ExtractTextResponse}
     */
    ExtractTextResponse: ExtractTextResponse,
    /**
     * The ExtractedBarcodeItem model constructor.
     * @property {module:model/ExtractedBarcodeItem}
     */
    ExtractedBarcodeItem: ExtractedBarcodeItem,
    /**
     * The ExtractedTextPage model constructor.
     * @property {module:model/ExtractedTextPage}
     */
    ExtractedTextPage: ExtractedTextPage,
    /**
     * The FieldToExtract model constructor.
     * @property {module:model/FieldToExtract}
     */
    FieldToExtract: FieldToExtract,
    /**
     * The FieldValue model constructor.
     * @property {module:model/FieldValue}
     */
    FieldValue: FieldValue,
    /**
     * The PolicyRule model constructor.
     * @property {module:model/PolicyRule}
     */
    PolicyRule: PolicyRule,
    /**
     * The PolicyRuleViolation model constructor.
     * @property {module:model/PolicyRuleViolation}
     */
    PolicyRuleViolation: PolicyRuleViolation,
    /**
     * The SummarizeDocumentResponse model constructor.
     * @property {module:model/SummarizeDocumentResponse}
     */
    SummarizeDocumentResponse: SummarizeDocumentResponse,
    /**
     * The TableResult model constructor.
     * @property {module:model/TableResult}
     */
    TableResult: TableResult,
    /**
     * The TableResultCell model constructor.
     * @property {module:model/TableResultCell}
     */
    TableResultCell: TableResultCell,
    /**
     * The TableResultRow model constructor.
     * @property {module:model/TableResultRow}
     */
    TableResultRow: TableResultRow,
    /**
     * The AnalyzeApi service constructor.
     * @property {module:api/AnalyzeApi}
     */
    AnalyzeApi: AnalyzeApi,
    /**
     * The ExtractApi service constructor.
     * @property {module:api/ExtractApi}
     */
    ExtractApi: ExtractApi,
    /**
     * The RunBatchJobApi service constructor.
     * @property {module:api/RunBatchJobApi}
     */
    RunBatchJobApi: RunBatchJobApi
  };

  return exports;
}));
