/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveDocumentaiApiClient);
  }
}(this, function(expect, CloudmersiveDocumentaiApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExtractDocumentJobStatusResult', function() {
    it('should create an instance of ExtractDocumentJobStatusResult', function() {
      // uncomment below and update the code to test ExtractDocumentJobStatusResult
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be.a(CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property asyncJobStatus (base name: "AsyncJobStatus")', function() {
      // uncomment below and update the code to test the property asyncJobStatus
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property asyncJobID (base name: "AsyncJobID")', function() {
      // uncomment below and update the code to test the property asyncJobID
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property extractTextResult (base name: "ExtractTextResult")', function() {
      // uncomment below and update the code to test the property extractTextResult
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property extractFieldsAndTablesResult (base name: "ExtractFieldsAndTablesResult")', function() {
      // uncomment below and update the code to test the property extractFieldsAndTablesResult
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property extractFieldsResult (base name: "ExtractFieldsResult")', function() {
      // uncomment below and update the code to test the property extractFieldsResult
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property extractClassificationResult (base name: "ExtractClassificationResult")', function() {
      // uncomment below and update the code to test the property extractClassificationResult
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "ErrorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult();
      //expect(instance).to.be();
    });

  });

}));
