/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveDocumentaiApiClient);
  }
}(this, function(expect, CloudmersiveDocumentaiApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveDocumentaiApiClient.PolicyRule();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PolicyRule', function() {
    it('should create an instance of PolicyRule', function() {
      // uncomment below and update the code to test PolicyRule
      //var instane = new CloudmersiveDocumentaiApiClient.PolicyRule();
      //expect(instance).to.be.a(CloudmersiveDocumentaiApiClient.PolicyRule);
    });

    it('should have the property ruleId (base name: "RuleId")', function() {
      // uncomment below and update the code to test the property ruleId
      //var instane = new CloudmersiveDocumentaiApiClient.PolicyRule();
      //expect(instance).to.be();
    });

    it('should have the property ruleType (base name: "RuleType")', function() {
      // uncomment below and update the code to test the property ruleType
      //var instane = new CloudmersiveDocumentaiApiClient.PolicyRule();
      //expect(instance).to.be();
    });

    it('should have the property ruleDescription (base name: "RuleDescription")', function() {
      // uncomment below and update the code to test the property ruleDescription
      //var instane = new CloudmersiveDocumentaiApiClient.PolicyRule();
      //expect(instance).to.be();
    });

  });

}));
