/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveDocumentaiapiClient);
  }
}(this, function(expect, CloudmersiveDocumentaiapiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveDocumentaiapiClient.ExtractApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExtractApi', function() {
    describe('extractAllFieldsAndTables', function() {
      it('should call extractAllFieldsAndTables successfully', function(done) {
        //uncomment below and update the code to test extractAllFieldsAndTables
        //instance.extractAllFieldsAndTables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractBarcodes', function() {
      it('should call extractBarcodes successfully', function(done) {
        //uncomment below and update the code to test extractBarcodes
        //instance.extractBarcodes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractClassification', function() {
      it('should call extractClassification successfully', function(done) {
        //uncomment below and update the code to test extractClassification
        //instance.extractClassification(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractClassificationAdvanced', function() {
      it('should call extractClassificationAdvanced successfully', function(done) {
        //uncomment below and update the code to test extractClassificationAdvanced
        //instance.extractClassificationAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractFields', function() {
      it('should call extractFields successfully', function(done) {
        //uncomment below and update the code to test extractFields
        //instance.extractFields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractFieldsAdvanced', function() {
      it('should call extractFieldsAdvanced successfully', function(done) {
        //uncomment below and update the code to test extractFieldsAdvanced
        //instance.extractFieldsAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractSummary', function() {
      it('should call extractSummary successfully', function(done) {
        //uncomment below and update the code to test extractSummary
        //instance.extractSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractTables', function() {
      it('should call extractTables successfully', function(done) {
        //uncomment below and update the code to test extractTables
        //instance.extractTables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractText', function() {
      it('should call extractText successfully', function(done) {
        //uncomment below and update the code to test extractText
        //instance.extractText(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
