/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveDocumentaiApiClient);
  }
}(this, function(expect, CloudmersiveDocumentaiApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveDocumentaiApiClient.RunBatchJobApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RunBatchJobApi', function() {
    describe('extractAllFieldsAndTablesFromDocumentBatchJob', function() {
      it('should call extractAllFieldsAndTablesFromDocumentBatchJob successfully', function(done) {
        //uncomment below and update the code to test extractAllFieldsAndTablesFromDocumentBatchJob
        //instance.extractAllFieldsAndTablesFromDocumentBatchJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractClassificationFromDocumentBatchJob', function() {
      it('should call extractClassificationFromDocumentBatchJob successfully', function(done) {
        //uncomment below and update the code to test extractClassificationFromDocumentBatchJob
        //instance.extractClassificationFromDocumentBatchJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractFieldsFromDocumentAdvancedBatchJob', function() {
      it('should call extractFieldsFromDocumentAdvancedBatchJob successfully', function(done) {
        //uncomment below and update the code to test extractFieldsFromDocumentAdvancedBatchJob
        //instance.extractFieldsFromDocumentAdvancedBatchJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('extractTextFromDocumentBatchJob', function() {
      it('should call extractTextFromDocumentBatchJob successfully', function(done) {
        //uncomment below and update the code to test extractTextFromDocumentBatchJob
        //instance.extractTextFromDocumentBatchJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAsyncJobStatus', function() {
      it('should call getAsyncJobStatus successfully', function(done) {
        //uncomment below and update the code to test getAsyncJobStatus
        //instance.getAsyncJobStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
