/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FieldToExtract'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FieldToExtract'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.AdvancedExtractFieldsRequest = factory(root.CloudmersiveDocumentaiApiClient.ApiClient, root.CloudmersiveDocumentaiApiClient.FieldToExtract);
  }
}(this, function(ApiClient, FieldToExtract) {
  'use strict';




  /**
   * The AdvancedExtractFieldsRequest model module.
   * @module model/AdvancedExtractFieldsRequest
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>AdvancedExtractFieldsRequest</code>.
   * Request to perform an AI field extraction on a document
   * @alias module:model/AdvancedExtractFieldsRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>AdvancedExtractFieldsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdvancedExtractFieldsRequest} obj Optional instance to populate.
   * @return {module:model/AdvancedExtractFieldsRequest} The populated <code>AdvancedExtractFieldsRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('InputFile')) {
        obj['InputFile'] = ApiClient.convertToType(data['InputFile'], 'Blob');
      }
      if (data.hasOwnProperty('FieldsToExtract')) {
        obj['FieldsToExtract'] = ApiClient.convertToType(data['FieldsToExtract'], [FieldToExtract]);
      }
      if (data.hasOwnProperty('MaximumPagesProcessed')) {
        obj['MaximumPagesProcessed'] = ApiClient.convertToType(data['MaximumPagesProcessed'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Input document file to perform the operation on as a byte array
   * @member {Blob} InputFile
   */
  exports.prototype['InputFile'] = undefined;
  /**
   * Fields to extract from the document
   * @member {Array.<module:model/FieldToExtract>} FieldsToExtract
   */
  exports.prototype['FieldsToExtract'] = undefined;
  /**
   * Optional: Limit the number of pages processed
   * @member {Number} MaximumPagesProcessed
   */
  exports.prototype['MaximumPagesProcessed'] = undefined;



  return exports;
}));


