/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PolicyRuleViolation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PolicyRuleViolation'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.DocumentPolicyResult = factory(root.CloudmersiveDocumentaiApiClient.ApiClient, root.CloudmersiveDocumentaiApiClient.PolicyRuleViolation);
  }
}(this, function(ApiClient, PolicyRuleViolation) {
  'use strict';




  /**
   * The DocumentPolicyResult model module.
   * @module model/DocumentPolicyResult
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>DocumentPolicyResult</code>.
   * Result of performing a document policy enforcement operation
   * @alias module:model/DocumentPolicyResult
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>DocumentPolicyResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentPolicyResult} obj Optional instance to populate.
   * @return {module:model/DocumentPolicyResult} The populated <code>DocumentPolicyResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CleanResult')) {
        obj['CleanResult'] = ApiClient.convertToType(data['CleanResult'], 'Boolean');
      }
      if (data.hasOwnProperty('RiskScore')) {
        obj['RiskScore'] = ApiClient.convertToType(data['RiskScore'], 'Number');
      }
      if (data.hasOwnProperty('RuleViolations')) {
        obj['RuleViolations'] = ApiClient.convertToType(data['RuleViolations'], [PolicyRuleViolation]);
      }
    }
    return obj;
  }

  /**
   * True if the document complies with all of the policies, and false if it does not
   * @member {Boolean} CleanResult
   */
  exports.prototype['CleanResult'] = undefined;
  /**
   * Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk
   * @member {Number} RiskScore
   */
  exports.prototype['RiskScore'] = undefined;
  /**
   * Policy violations
   * @member {Array.<module:model/PolicyRuleViolation>} RuleViolations
   */
  exports.prototype['RuleViolations'] = undefined;



  return exports;
}));


