/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PolicyRule'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PolicyRule'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.DocumentPolicyRequest = factory(root.CloudmersiveDocumentaiapiClient.ApiClient, root.CloudmersiveDocumentaiapiClient.PolicyRule);
  }
}(this, function(ApiClient, PolicyRule) {
  'use strict';




  /**
   * The DocumentPolicyRequest model module.
   * @module model/DocumentPolicyRequest
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>DocumentPolicyRequest</code>.
   * Request to analyze a document
   * @alias module:model/DocumentPolicyRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>DocumentPolicyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentPolicyRequest} obj Optional instance to populate.
   * @return {module:model/DocumentPolicyRequest} The populated <code>DocumentPolicyRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('InputFile')) {
        obj['InputFile'] = ApiClient.convertToType(data['InputFile'], 'Blob');
      }
      if (data.hasOwnProperty('Rules')) {
        obj['Rules'] = ApiClient.convertToType(data['Rules'], [PolicyRule]);
      }
    }
    return obj;
  }

  /**
   * Input file as a byte array
   * @member {Blob} InputFile
   */
  exports.prototype['InputFile'] = undefined;
  /**
   * Rules to apply to the document
   * @member {Array.<module:model/PolicyRule>} Rules
   */
  exports.prototype['Rules'] = undefined;



  return exports;
}));


