/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.DocumentCategories = factory(root.CloudmersiveDocumentaiapiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DocumentCategories model module.
   * @module model/DocumentCategories
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>DocumentCategories</code>.
   * Document category option
   * @alias module:model/DocumentCategories
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>DocumentCategories</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentCategories} obj Optional instance to populate.
   * @return {module:model/DocumentCategories} The populated <code>DocumentCategories</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CategoryName')) {
        obj['CategoryName'] = ApiClient.convertToType(data['CategoryName'], 'String');
      }
      if (data.hasOwnProperty('CategoryDescription')) {
        obj['CategoryDescription'] = ApiClient.convertToType(data['CategoryDescription'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the classification
   * @member {String} CategoryName
   */
  exports.prototype['CategoryName'] = undefined;
  /**
   * Optional but recommended: Description of the classification in natural langugage
   * @member {String} CategoryDescription
   */
  exports.prototype['CategoryDescription'] = undefined;



  return exports;
}));


