/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExtractedBarcodeItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExtractedBarcodeItem'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.ExtractBarcodesAiResponse = factory(root.CloudmersiveDocumentaiapiClient.ApiClient, root.CloudmersiveDocumentaiapiClient.ExtractedBarcodeItem);
  }
}(this, function(ApiClient, ExtractedBarcodeItem) {
  'use strict';




  /**
   * The ExtractBarcodesAiResponse model module.
   * @module model/ExtractBarcodesAiResponse
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>ExtractBarcodesAiResponse</code>.
   * Result of extracting barcodes from a document
   * @alias module:model/ExtractBarcodesAiResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ExtractBarcodesAiResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtractBarcodesAiResponse} obj Optional instance to populate.
   * @return {module:model/ExtractBarcodesAiResponse} The populated <code>ExtractBarcodesAiResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('BarcodeResults')) {
        obj['BarcodeResults'] = ApiClient.convertToType(data['BarcodeResults'], [ExtractedBarcodeItem]);
      }
    }
    return obj;
  }

  /**
   * True if successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * Table value results from the extraction operation
   * @member {Array.<module:model/ExtractedBarcodeItem>} BarcodeResults
   */
  exports.prototype['BarcodeResults'] = undefined;



  return exports;
}));


