/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DocumentClassificationResult', 'model/ExtractFieldsAndTablesResponse', 'model/ExtractFieldsResponse', 'model/ExtractTextResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DocumentClassificationResult'), require('./ExtractFieldsAndTablesResponse'), require('./ExtractFieldsResponse'), require('./ExtractTextResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult = factory(root.CloudmersiveDocumentaiApiClient.ApiClient, root.CloudmersiveDocumentaiApiClient.DocumentClassificationResult, root.CloudmersiveDocumentaiApiClient.ExtractFieldsAndTablesResponse, root.CloudmersiveDocumentaiApiClient.ExtractFieldsResponse, root.CloudmersiveDocumentaiApiClient.ExtractTextResponse);
  }
}(this, function(ApiClient, DocumentClassificationResult, ExtractFieldsAndTablesResponse, ExtractFieldsResponse, ExtractTextResponse) {
  'use strict';




  /**
   * The ExtractDocumentJobStatusResult model module.
   * @module model/ExtractDocumentJobStatusResult
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>ExtractDocumentJobStatusResult</code>.
   * Result of performing a batch job operation
   * @alias module:model/ExtractDocumentJobStatusResult
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>ExtractDocumentJobStatusResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtractDocumentJobStatusResult} obj Optional instance to populate.
   * @return {module:model/ExtractDocumentJobStatusResult} The populated <code>ExtractDocumentJobStatusResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('AsyncJobStatus')) {
        obj['AsyncJobStatus'] = ApiClient.convertToType(data['AsyncJobStatus'], 'String');
      }
      if (data.hasOwnProperty('AsyncJobID')) {
        obj['AsyncJobID'] = ApiClient.convertToType(data['AsyncJobID'], 'String');
      }
      if (data.hasOwnProperty('ExtractTextResult')) {
        obj['ExtractTextResult'] = ExtractTextResponse.constructFromObject(data['ExtractTextResult']);
      }
      if (data.hasOwnProperty('ExtractFieldsAndTablesResult')) {
        obj['ExtractFieldsAndTablesResult'] = ExtractFieldsAndTablesResponse.constructFromObject(data['ExtractFieldsAndTablesResult']);
      }
      if (data.hasOwnProperty('ExtractFieldsResult')) {
        obj['ExtractFieldsResult'] = ExtractFieldsResponse.constructFromObject(data['ExtractFieldsResult']);
      }
      if (data.hasOwnProperty('ExtractClassificationResult')) {
        obj['ExtractClassificationResult'] = DocumentClassificationResult.constructFromObject(data['ExtractClassificationResult']);
      }
      if (data.hasOwnProperty('ErrorMessage')) {
        obj['ErrorMessage'] = ApiClient.convertToType(data['ErrorMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * True if the operation to check the status of the job was successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
   * @member {String} AsyncJobStatus
   */
  exports.prototype['AsyncJobStatus'] = undefined;
  /**
   * Job ID
   * @member {String} AsyncJobID
   */
  exports.prototype['AsyncJobID'] = undefined;
  /**
   * @member {module:model/ExtractTextResponse} ExtractTextResult
   */
  exports.prototype['ExtractTextResult'] = undefined;
  /**
   * @member {module:model/ExtractFieldsAndTablesResponse} ExtractFieldsAndTablesResult
   */
  exports.prototype['ExtractFieldsAndTablesResult'] = undefined;
  /**
   * @member {module:model/ExtractFieldsResponse} ExtractFieldsResult
   */
  exports.prototype['ExtractFieldsResult'] = undefined;
  /**
   * @member {module:model/DocumentClassificationResult} ExtractClassificationResult
   */
  exports.prototype['ExtractClassificationResult'] = undefined;
  /**
   * Error message (if any)
   * @member {String} ErrorMessage
   */
  exports.prototype['ErrorMessage'] = undefined;



  return exports;
}));


