/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.ExtractedBarcodeItem = factory(root.CloudmersiveDocumentaiApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExtractedBarcodeItem model module.
   * @module model/ExtractedBarcodeItem
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>ExtractedBarcodeItem</code>.
   * Extracted barcode result
   * @alias module:model/ExtractedBarcodeItem
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ExtractedBarcodeItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtractedBarcodeItem} obj Optional instance to populate.
   * @return {module:model/ExtractedBarcodeItem} The populated <code>ExtractedBarcodeItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('BarcodeType')) {
        obj['BarcodeType'] = ApiClient.convertToType(data['BarcodeType'], 'String');
      }
      if (data.hasOwnProperty('BarcodeValue')) {
        obj['BarcodeValue'] = ApiClient.convertToType(data['BarcodeValue'], 'String');
      }
    }
    return obj;
  }

  /**
   * Type of the barcode identified, possible values are: AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB, UNKNOWN
   * @member {String} BarcodeType
   */
  exports.prototype['BarcodeType'] = undefined;
  /**
   * Value of the barcode as a string
   * @member {String} BarcodeValue
   */
  exports.prototype['BarcodeValue'] = undefined;



  return exports;
}));


