/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.ExtractDocumentBatchJobResult = factory(root.CloudmersiveDocumentaiapiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExtractDocumentBatchJobResult model module.
   * @module model/ExtractDocumentBatchJobResult
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>ExtractDocumentBatchJobResult</code>.
   * Result of performing a split document batch job
   * @alias module:model/ExtractDocumentBatchJobResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ExtractDocumentBatchJobResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtractDocumentBatchJobResult} obj Optional instance to populate.
   * @return {module:model/ExtractDocumentBatchJobResult} The populated <code>ExtractDocumentBatchJobResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('AsyncJobID')) {
        obj['AsyncJobID'] = ApiClient.convertToType(data['AsyncJobID'], 'String');
      }
    }
    return obj;
  }

  /**
   * True if successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * When creating a job, an Async Job ID is returned.  Use the GetAsyncJobStatus API to check on the status of this job using the AsyncJobID and get the result when it finishes
   * @member {String} AsyncJobID
   */
  exports.prototype['AsyncJobID'] = undefined;



  return exports;
}));


