/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.FieldValue = factory(root.CloudmersiveDocumentaiApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FieldValue model module.
   * @module model/FieldValue
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>FieldValue</code>.
   * Field value result of extracting fields from a document
   * @alias module:model/FieldValue
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>FieldValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FieldValue} obj Optional instance to populate.
   * @return {module:model/FieldValue} The populated <code>FieldValue</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('FieldName')) {
        obj['FieldName'] = ApiClient.convertToType(data['FieldName'], 'String');
      }
      if (data.hasOwnProperty('FieldStringValue')) {
        obj['FieldStringValue'] = ApiClient.convertToType(data['FieldStringValue'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the field (note that spaces will be replaced with underscore)
   * @member {String} FieldName
   */
  exports.prototype['FieldName'] = undefined;
  /**
   * String value of the field that was extractged from the document
   * @member {String} FieldStringValue
   */
  exports.prototype['FieldStringValue'] = undefined;



  return exports;
}));


