/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.FieldToExtract = factory(root.CloudmersiveDocumentaiApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FieldToExtract model module.
   * @module model/FieldToExtract
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>FieldToExtract</code>.
   * Field to extract from a document using AI
   * @alias module:model/FieldToExtract
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>FieldToExtract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FieldToExtract} obj Optional instance to populate.
   * @return {module:model/FieldToExtract} The populated <code>FieldToExtract</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('FieldName')) {
        obj['FieldName'] = ApiClient.convertToType(data['FieldName'], 'String');
      }
      if (data.hasOwnProperty('FieldOptional')) {
        obj['FieldOptional'] = ApiClient.convertToType(data['FieldOptional'], 'Boolean');
      }
      if (data.hasOwnProperty('FieldDescription')) {
        obj['FieldDescription'] = ApiClient.convertToType(data['FieldDescription'], 'String');
      }
      if (data.hasOwnProperty('FieldExample')) {
        obj['FieldExample'] = ApiClient.convertToType(data['FieldExample'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the field to extract
   * @member {String} FieldName
   */
  exports.prototype['FieldName'] = undefined;
  /**
   * Optional: True if the field is optional, false if required (default)
   * @member {Boolean} FieldOptional
   */
  exports.prototype['FieldOptional'] = undefined;
  /**
   * Optional but recommended: Description of the field - use this to describe what the field is, how it is formatted, what is unique about it, etc.
   * @member {String} FieldDescription
   */
  exports.prototype['FieldDescription'] = undefined;
  /**
   * Optional: Example label or value of the field
   * @member {String} FieldExample
   */
  exports.prototype['FieldExample'] = undefined;



  return exports;
}));


