/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.PolicyRule = factory(root.CloudmersiveDocumentaiapiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PolicyRule model module.
   * @module model/PolicyRule
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>PolicyRule</code>.
   * @alias module:model/PolicyRule
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PolicyRule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PolicyRule} obj Optional instance to populate.
   * @return {module:model/PolicyRule} The populated <code>PolicyRule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('RuleId')) {
        obj['RuleId'] = ApiClient.convertToType(data['RuleId'], 'String');
      }
      if (data.hasOwnProperty('RuleType')) {
        obj['RuleType'] = ApiClient.convertToType(data['RuleType'], 'String');
      }
      if (data.hasOwnProperty('RuleDescription')) {
        obj['RuleDescription'] = ApiClient.convertToType(data['RuleDescription'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} RuleId
   */
  exports.prototype['RuleId'] = undefined;
  /**
   * Possible values are ALLOW and DENY
   * @member {String} RuleType
   */
  exports.prototype['RuleType'] = undefined;
  /**
   * Description of the rule in natural language, e.g. Do not allow documents that contain offensive language
   * @member {String} RuleDescription
   */
  exports.prototype['RuleDescription'] = undefined;



  return exports;
}));


