/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.PolicyRuleViolation = factory(root.CloudmersiveDocumentaiApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PolicyRuleViolation model module.
   * @module model/PolicyRuleViolation
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>PolicyRuleViolation</code>.
   * Instances of a policy rule violation
   * @alias module:model/PolicyRuleViolation
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PolicyRuleViolation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PolicyRuleViolation} obj Optional instance to populate.
   * @return {module:model/PolicyRuleViolation} The populated <code>PolicyRuleViolation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('RuleId')) {
        obj['RuleId'] = ApiClient.convertToType(data['RuleId'], 'String');
      }
      if (data.hasOwnProperty('RuleViolationRiskScore')) {
        obj['RuleViolationRiskScore'] = ApiClient.convertToType(data['RuleViolationRiskScore'], 'Number');
      }
      if (data.hasOwnProperty('RuleViolationRationale')) {
        obj['RuleViolationRationale'] = ApiClient.convertToType(data['RuleViolationRationale'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of the rule; if no ID was supplied, the ID is the 1-based index of the rule
   * @member {String} RuleId
   */
  exports.prototype['RuleId'] = undefined;
  /**
   * Risk score between 0.0 and 1.0 where values above 0.5 are increasing levels of risk
   * @member {Number} RuleViolationRiskScore
   */
  exports.prototype['RuleViolationRiskScore'] = undefined;
  /**
   * AI natural language rationale for why this policy was violated
   * @member {String} RuleViolationRationale
   */
  exports.prototype['RuleViolationRationale'] = undefined;



  return exports;
}));


