/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.TableResultCell = factory(root.CloudmersiveDocumentaiApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TableResultCell model module.
   * @module model/TableResultCell
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>TableResultCell</code>.
   * Cell of a row of a table extracted from a document
   * @alias module:model/TableResultCell
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TableResultCell</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TableResultCell} obj Optional instance to populate.
   * @return {module:model/TableResultCell} The populated <code>TableResultCell</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CellHeader')) {
        obj['CellHeader'] = ApiClient.convertToType(data['CellHeader'], 'String');
      }
      if (data.hasOwnProperty('CellValue')) {
        obj['CellValue'] = ApiClient.convertToType(data['CellValue'], 'String');
      }
    }
    return obj;
  }

  /**
   * Cell column header
   * @member {String} CellHeader
   */
  exports.prototype['CellHeader'] = undefined;
  /**
   * Cell value as a string
   * @member {String} CellValue
   */
  exports.prototype['CellValue'] = undefined;



  return exports;
}));


