/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TableResultCell'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TableResultCell'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.TableResultRow = factory(root.CloudmersiveDocumentaiapiClient.ApiClient, root.CloudmersiveDocumentaiapiClient.TableResultCell);
  }
}(this, function(ApiClient, TableResultCell) {
  'use strict';




  /**
   * The TableResultRow model module.
   * @module model/TableResultRow
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>TableResultRow</code>.
   * Row of a table extracted from a document
   * @alias module:model/TableResultRow
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>TableResultRow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TableResultRow} obj Optional instance to populate.
   * @return {module:model/TableResultRow} The populated <code>TableResultRow</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Cells')) {
        obj['Cells'] = ApiClient.convertToType(data['Cells'], [TableResultCell]);
      }
    }
    return obj;
  }

  /**
   * Cells in the row
   * @member {Array.<module:model/TableResultCell>} Cells
   */
  exports.prototype['Cells'] = undefined;



  return exports;
}));


