/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TableResultRow'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TableResultRow'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.TableResult = factory(root.CloudmersiveDocumentaiapiClient.ApiClient, root.CloudmersiveDocumentaiapiClient.TableResultRow);
  }
}(this, function(ApiClient, TableResultRow) {
  'use strict';




  /**
   * The TableResult model module.
   * @module model/TableResult
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>TableResult</code>.
   * Table extracted from a document
   * @alias module:model/TableResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TableResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TableResult} obj Optional instance to populate.
   * @return {module:model/TableResult} The populated <code>TableResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Title')) {
        obj['Title'] = ApiClient.convertToType(data['Title'], 'String');
      }
      if (data.hasOwnProperty('Rows')) {
        obj['Rows'] = ApiClient.convertToType(data['Rows'], [TableResultRow]);
      }
    }
    return obj;
  }

  /**
   * Title of the table (optional)
   * @member {String} Title
   */
  exports.prototype['Title'] = undefined;
  /**
   * Rows of the table
   * @member {Array.<module:model/TableResultRow>} Rows
   */
  exports.prototype['Rows'] = undefined;



  return exports;
}));


