/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DocumentPolicyRequest', 'model/DocumentPolicyResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DocumentPolicyRequest'), require('../model/DocumentPolicyResult'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.AnalyzeApi = factory(root.CloudmersiveDocumentaiapiClient.ApiClient, root.CloudmersiveDocumentaiapiClient.DocumentPolicyRequest, root.CloudmersiveDocumentaiapiClient.DocumentPolicyResult);
  }
}(this, function(ApiClient, DocumentPolicyRequest, DocumentPolicyResult) {
  'use strict';

  /**
   * Analyze service.
   * @module api/AnalyzeApi
   * @version 1.3.0
   */

  /**
   * Constructs a new AnalyzeApi. 
   * @alias module:api/AnalyzeApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the applyRules operation.
     * @callback module:api/AnalyzeApi~applyRulesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DocumentPolicyResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Enforce Policies to a Document to allow or block it using Advanced AI
     * Enforce Policies to a Document to allow or block it using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {module:model/DocumentPolicyRequest} opts.body Input request, including document and policy rules
     * @param {module:api/AnalyzeApi~applyRulesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DocumentPolicyResult}
     */
    this.applyRules = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = DocumentPolicyResult;

      return this.apiClient.callApi(
        '/document-ai/document/analyze/enforce-policy', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
