/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdvancedExtractClassificationRequest', 'model/AdvancedExtractFieldsRequest', 'model/DocumentAdvancedClassificationResult', 'model/DocumentClassificationResult', 'model/ExtractBarcodesAiResponse', 'model/ExtractFieldsAndTablesResponse', 'model/ExtractFieldsResponse', 'model/ExtractTablesResponse', 'model/ExtractTextResponse', 'model/SummarizeDocumentResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AdvancedExtractClassificationRequest'), require('../model/AdvancedExtractFieldsRequest'), require('../model/DocumentAdvancedClassificationResult'), require('../model/DocumentClassificationResult'), require('../model/ExtractBarcodesAiResponse'), require('../model/ExtractFieldsAndTablesResponse'), require('../model/ExtractFieldsResponse'), require('../model/ExtractTablesResponse'), require('../model/ExtractTextResponse'), require('../model/SummarizeDocumentResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiapiClient) {
      root.CloudmersiveDocumentaiapiClient = {};
    }
    root.CloudmersiveDocumentaiapiClient.ExtractApi = factory(root.CloudmersiveDocumentaiapiClient.ApiClient, root.CloudmersiveDocumentaiapiClient.AdvancedExtractClassificationRequest, root.CloudmersiveDocumentaiapiClient.AdvancedExtractFieldsRequest, root.CloudmersiveDocumentaiapiClient.DocumentAdvancedClassificationResult, root.CloudmersiveDocumentaiapiClient.DocumentClassificationResult, root.CloudmersiveDocumentaiapiClient.ExtractBarcodesAiResponse, root.CloudmersiveDocumentaiapiClient.ExtractFieldsAndTablesResponse, root.CloudmersiveDocumentaiapiClient.ExtractFieldsResponse, root.CloudmersiveDocumentaiapiClient.ExtractTablesResponse, root.CloudmersiveDocumentaiapiClient.ExtractTextResponse, root.CloudmersiveDocumentaiapiClient.SummarizeDocumentResponse);
  }
}(this, function(ApiClient, AdvancedExtractClassificationRequest, AdvancedExtractFieldsRequest, DocumentAdvancedClassificationResult, DocumentClassificationResult, ExtractBarcodesAiResponse, ExtractFieldsAndTablesResponse, ExtractFieldsResponse, ExtractTablesResponse, ExtractTextResponse, SummarizeDocumentResponse) {
  'use strict';

  /**
   * Extract service.
   * @module api/ExtractApi
   * @version 1.3.0
   */

  /**
   * Constructs a new ExtractApi. 
   * @alias module:api/ExtractApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the extractAllFieldsAndTables operation.
     * @callback module:api/ExtractApi~extractAllFieldsAndTablesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractFieldsAndTablesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract All Fields and Tables of Data from a Document using AI
     * Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/ExtractApi~extractAllFieldsAndTablesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractFieldsAndTablesResponse}
     */
    this.extractAllFieldsAndTables = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractFieldsAndTablesResponse;

      return this.apiClient.callApi(
        '/document-ai/document/extract/all', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractBarcodes operation.
     * @callback module:api/ExtractApi~extractBarcodesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractBarcodesAiResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Barcodes of from a Document using AI
     * Extract all barcodes from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/ExtractApi~extractBarcodesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractBarcodesAiResponse}
     */
    this.extractBarcodes = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractBarcodesAiResponse;

      return this.apiClient.callApi(
        '/document-ai/document/extract/barcodes', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractClassification operation.
     * @callback module:api/ExtractApi~extractClassificationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DocumentClassificationResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Classification or Category from a Document using AI
     * Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.categories Desired classification to extract
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/ExtractApi~extractClassificationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DocumentClassificationResult}
     */
    this.extractClassification = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Categories': opts['categories'],
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = DocumentClassificationResult;

      return this.apiClient.callApi(
        '/document-ai/document/extract/classify', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractClassificationAdvanced operation.
     * @callback module:api/ExtractApi~extractClassificationAdvancedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DocumentAdvancedClassificationResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Classification or Category from a Document using Advanced AI
     * Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {module:model/AdvancedExtractClassificationRequest} opts.body Input request to perform the classification on
     * @param {module:api/ExtractApi~extractClassificationAdvancedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DocumentAdvancedClassificationResult}
     */
    this.extractClassificationAdvanced = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = DocumentAdvancedClassificationResult;

      return this.apiClient.callApi(
        '/document-ai/document/extract/classify/advanced', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractFields operation.
     * @callback module:api/ExtractApi~extractFieldsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractFieldsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Field Values from a Document using AI
     * Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.fieldNames Desired fields to extract, comma separated
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/ExtractApi~extractFieldsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractFieldsResponse}
     */
    this.extractFields = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'FieldNames': opts['fieldNames'],
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractFieldsResponse;

      return this.apiClient.callApi(
        '/document-ai/document/extract/fields', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractFieldsAdvanced operation.
     * @callback module:api/ExtractApi~extractFieldsAdvancedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractFieldsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Field Values from a Document using Advanced AI
     * Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {module:model/AdvancedExtractFieldsRequest} opts.body Input request, including document file as byte array, and information on which fields to extract
     * @param {module:api/ExtractApi~extractFieldsAdvancedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractFieldsResponse}
     */
    this.extractFieldsAdvanced = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractFieldsResponse;

      return this.apiClient.callApi(
        '/document-ai/document/extract/fields/advanced', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractSummary operation.
     * @callback module:api/ExtractApi~extractSummaryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SummarizeDocumentResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Summary from a Document using AI
     * Creates a 1 paragraph summary of the input document using Artificial Intelligence.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/ExtractApi~extractSummaryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SummarizeDocumentResponse}
     */
    this.extractSummary = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = SummarizeDocumentResponse;

      return this.apiClient.callApi(
        '/document-ai/document/extract/summary', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractTables operation.
     * @callback module:api/ExtractApi~extractTablesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractTablesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Tables of Data from a Document using AI
     * Extract Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/ExtractApi~extractTablesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractTablesResponse}
     */
    this.extractTables = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractTablesResponse;

      return this.apiClient.callApi(
        '/document-ai/document/extract/tables', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractText operation.
     * @callback module:api/ExtractApi~extractTextCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractTextResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Text from a Document using AI
     * Extract raw text from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/ExtractApi~extractTextCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractTextResponse}
     */
    this.extractText = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractTextResponse;

      return this.apiClient.callApi(
        '/document-ai/document/extract/text', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
