/**
 * Document AI API
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdvancedExtractFieldsRequest', 'model/ExtractDocumentBatchJobResult', 'model/ExtractDocumentJobStatusResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AdvancedExtractFieldsRequest'), require('../model/ExtractDocumentBatchJobResult'), require('../model/ExtractDocumentJobStatusResult'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDocumentaiApiClient) {
      root.CloudmersiveDocumentaiApiClient = {};
    }
    root.CloudmersiveDocumentaiApiClient.RunBatchJobApi = factory(root.CloudmersiveDocumentaiApiClient.ApiClient, root.CloudmersiveDocumentaiApiClient.AdvancedExtractFieldsRequest, root.CloudmersiveDocumentaiApiClient.ExtractDocumentBatchJobResult, root.CloudmersiveDocumentaiApiClient.ExtractDocumentJobStatusResult);
  }
}(this, function(ApiClient, AdvancedExtractFieldsRequest, ExtractDocumentBatchJobResult, ExtractDocumentJobStatusResult) {
  'use strict';

  /**
   * RunBatchJob service.
   * @module api/RunBatchJobApi
   * @version 1.3.1
   */

  /**
   * Constructs a new RunBatchJobApi. 
   * @alias module:api/RunBatchJobApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the extractAllFieldsAndTablesFromDocumentBatchJob operation.
     * @callback module:api/RunBatchJobApi~extractAllFieldsAndTablesFromDocumentBatchJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractDocumentBatchJobResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract All Fields and Tables of Data from a Document using AI as a Batch Job
     * Creates an async batch job for processing a large document as an AI batch job.  Extract all Fields and Tables, comprised of rows and columns of data, from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/RunBatchJobApi~extractAllFieldsAndTablesFromDocumentBatchJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractDocumentBatchJobResult}
     */
    this.extractAllFieldsAndTablesFromDocumentBatchJob = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractDocumentBatchJobResult;

      return this.apiClient.callApi(
        '/document-ai/document/batch-job/extract/all', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractClassificationFromDocumentBatchJob operation.
     * @callback module:api/RunBatchJobApi~extractClassificationFromDocumentBatchJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractDocumentBatchJobResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Classification or Category from a Document using AI as a Batch Job
     * Creates an async batch job for processing a large document as an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt, Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.categories Desired classification to extract
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/RunBatchJobApi~extractClassificationFromDocumentBatchJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractDocumentBatchJobResult}
     */
    this.extractClassificationFromDocumentBatchJob = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Categories': opts['categories'],
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractDocumentBatchJobResult;

      return this.apiClient.callApi(
        '/document-ai/document/batch-job/extract/classify', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractFieldsFromDocumentAdvancedBatchJob operation.
     * @callback module:api/RunBatchJobApi~extractFieldsFromDocumentAdvancedBatchJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractDocumentBatchJobResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Field Values from a Document using Advanced AI as a Batch Job
     * Creates an async batch job for processing a large document as an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date, Business Card Phone Number, etc.) from a document using Advanced AI.  Input document formats supported include DOCX, PDF, PNG and JPG.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {module:model/AdvancedExtractFieldsRequest} opts.body 
     * @param {module:api/RunBatchJobApi~extractFieldsFromDocumentAdvancedBatchJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractDocumentBatchJobResult}
     */
    this.extractFieldsFromDocumentAdvancedBatchJob = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractDocumentBatchJobResult;

      return this.apiClient.callApi(
        '/document-ai/document/batch-job/extract/fields/advanced', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the extractTextFromDocumentBatchJob operation.
     * @callback module:api/RunBatchJobApi~extractTextFromDocumentBatchJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractDocumentBatchJobResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Extract Text from a Document using AI as a Batch Job
     * Creates an async batch job for processing a large document as an AI batch job.  Input document formats supported include DOCX, PDF, PNG and JPG.  Supports a wide range of languages.
     * @param {Object} opts Optional parameters
     * @param {String} opts.recognitionMode Optional; Recognition mode - Advanced (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/RunBatchJobApi~extractTextFromDocumentBatchJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractDocumentBatchJobResult}
     */
    this.extractTextFromDocumentBatchJob = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'recognitionMode': opts['recognitionMode']
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractDocumentBatchJobResult;

      return this.apiClient.callApi(
        '/document-ai/document/batch-job/extract/text', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAsyncJobStatus operation.
     * @callback module:api/RunBatchJobApi~getAsyncJobStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExtractDocumentJobStatusResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the status and result of an Extract Document Batch Job
     * Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
     * @param {Object} opts Optional parameters
     * @param {String} opts.asyncJobID 
     * @param {module:api/RunBatchJobApi~getAsyncJobStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExtractDocumentJobStatusResult}
     */
    this.getAsyncJobStatus = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'AsyncJobID': opts['asyncJobID'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = ExtractDocumentJobStatusResult;

      return this.apiClient.callApi(
        '/document-ai/document/batch-job/batch-job/status', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
